export type SkillCategory = "genai" | "ml" | "data" | "dev" | "tools";

export const skillGroups: { category: SkillCategory; items: string[] }[] = [
  {
    category: "genai",
    items: [
      "LangGraph",
      "LangChain",
      "PydanticAI",
      "Qdrant",
      "BM25",
      "OpenAI",
      "Cohere",
      "RAG naïf",
      "RAG correctif",
      "RAG hybride",
      "Contextual Retrieval",
      "Prompt engineering",
      "LLM-as-judge",
      "FastAPI",
      "Langfuse",
    ],
  },
  {
    category: "ml",
    items: [
      "Python",
      "scikit-learn",
      "XGBoost",
      "TensorFlow",
      "Keras",
      "pandas",
      "Feature engineering",
      "SMOTE",
      "Class weighting",
      "Hypothesis",
      "MLOps",
    ],
  },
  {
    category: "data",
    items: [
      "Pipelines de données",
      "ETL",
      "SQL",
      "PostgreSQL",
      "Snowflake",
      "DBeaver",
      "UiPath / RPA",
    ],
  },
  {
    category: "dev",
    items: [
      "Node.js",
      "Next.js",
      "JavaScript",
      "TypeScript",
      "API design",
      "Génération DOCX/PPTX",
    ],
  },
  {
    category: "tools",
    items: [
      "GitLab",
      "Git",
      "Airflow",
      "ArgoCD",
      "Rancher",
      "Docker",
      "uv",
      "AWS",
      "Azure",
      "Salesforce",
      "SAP",
      "Power BI",
      "Tableau",
      "Alteryx",
      "Excel",
      "CI/CD",
    ],
  },
];
