import type { LucideIcon } from "lucide-react";
import {
  Search,
  Wand2,
  Activity,
  SlidersHorizontal,
  Shuffle,
  Scale,
  Workflow,
  Waypoints,
  RefreshCw,
  Database,
  FileText,
  Webhook,
  SearchCode,
  Sparkles,
  AudioLines,
  AudioWaveform,
  ChartLine,
  BarChart3,
  FileSpreadsheet,
  Hexagon,
  TrendingUp,
  ListFilter,
  ScanSearch,
  Gavel,
  Cloud,
  CloudCog,
  Building2,
  PieChart,
  LayoutDashboard,
  Layers,
  Rocket,
  Code2,
} from "lucide-react";
import {
  siPython,
  siTensorflow,
  siKeras,
  siScikitlearn,
  siPandas,
  siDocker,
  siGitlab,
  siApacheairflow,
  siNextdotjs,
  siNodedotjs,
  siTypescript,
  siJavascript,
  siFastapi,
  siLangchain,
  siQdrant,
  siUipath,
  siArgo,
  siRancher,
  siOpenapiinitiative,
  siPydantic,
  siLanggraph,
  siUv,
  siHypothesis,
  siPostgresql,
  siSnowflake,
  siDbeaver,
  siGit,
  siSap,
  type SimpleIcon,
} from "simple-icons";

export type TechIconEntry =
  | { kind: "brand"; icon: SimpleIcon }
  | { kind: "lucide"; icon: LucideIcon };

const brand = (icon: SimpleIcon): TechIconEntry => ({ kind: "brand", icon });
const lucide = (icon: LucideIcon): TechIconEntry => ({ kind: "lucide", icon });

// Exact matches, keyed by lowercased tech name as it appears in content.
const EXACT_MAP: Record<string, TechIconEntry> = {
  python: brand(siPython),
  tensorflow: brand(siTensorflow),
  keras: brand(siKeras),
  "scikit-learn": brand(siScikitlearn),
  pandas: brand(siPandas),
  docker: brand(siDocker),
  gitlab: brand(siGitlab),
  airflow: brand(siApacheairflow),
  "next.js": brand(siNextdotjs),
  "node.js": brand(siNodedotjs),
  typescript: brand(siTypescript),
  javascript: brand(siJavascript),
  fastapi: brand(siFastapi),
  langchain: brand(siLangchain),
  qdrant: brand(siQdrant),
  uipath: brand(siUipath),
  "uipath / rpa": brand(siUipath),
  argocd: brand(siArgo),
  rancher: brand(siRancher),
  openapi: brand(siOpenapiinitiative),
  pydantic: brand(siPydantic),
  pydanticai: brand(siPydantic),
  langgraph: brand(siLanggraph),
  uv: brand(siUv),
  hypothesis: brand(siHypothesis),
  postgresql: brand(siPostgresql),
  snowflake: brand(siSnowflake),
  dbeaver: brand(siDbeaver),
  git: brand(siGit),
  sap: brand(siSap),

  "rag naïf": lucide(Search),
  "rag correctif": lucide(Search),
  "rag hybride": lucide(Search),
  "prompt engineering": lucide(Wand2),
  langfuse: lucide(Activity),
  "feature engineering": lucide(SlidersHorizontal),
  smote: lucide(Shuffle),
  "class weighting": lucide(Scale),
  mlops: lucide(Workflow),
  "pipelines de données": lucide(Waypoints),
  etl: lucide(RefreshCw),
  sql: lucide(Database),
  "génération docx/pptx": lucide(FileText),
  "api design": lucide(Webhook),
  ripgrep: lucide(SearchCode),
  "openai api": lucide(Sparkles),
  openai: lucide(Sparkles),
  "openai whisper": lucide(Sparkles),
  cohere: lucide(Sparkles),
  "moteur tts neuronal": lucide(AudioLines),
  "webaudio api": lucide(AudioWaveform),
  "imbalanced-learn": lucide(Shuffle),
  matplotlib: lucide(ChartLine),
  seaborn: lucide(BarChart3),
  openpyxl: lucide(FileSpreadsheet),
  excel: lucide(FileSpreadsheet),
  "architecture hexagonale": lucide(Hexagon),
  xgboost: lucide(TrendingUp),
  bm25: lucide(ListFilter),
  "contextual retrieval": lucide(ScanSearch),
  "llm-as-judge": lucide(Gavel),
  aws: lucide(Cloud),
  azure: lucide(CloudCog),
  salesforce: lucide(Building2),
  "power bi": lucide(PieChart),
  tableau: lucide(LayoutDashboard),
  alteryx: lucide(Layers),
  "ci/cd": lucide(Rocket),
};

const DEFAULT_ICON: TechIconEntry = lucide(Code2);

export function getTechIcon(name: string): TechIconEntry {
  const key = name.trim().toLowerCase();
  return EXACT_MAP[key] ?? DEFAULT_ICON;
}
